const PLAYER_HEIGHT = 2;
const PLAYER_WIDTH = 0.4;
const SPEED = 25;
const SHIFT_MULTIPLIER = 1.5;

const CACODEMON_HEIGHT = 2;

export { PLAYER_HEIGHT, PLAYER_WIDTH, SPEED, SHIFT_MULTIPLIER, CACODEMON_HEIGHT };